// Code generated by goctl. DO NOT EDIT.
package types

type CreateURLRequest struct {
	OriginalRrl string `json:"original_url" validate:"required,url"`
	CustomCode  string `json:"custom_code,omitempty" validate:"omitempty,max=10,min=4,alphanum"`
	Duration    *int   `json:"duration,omitempty" validate:"omitempty,min=1,max=365"`
}

type CreateURLResponse struct {
	ShortLink string `json:"short_link"`
	ExpireAt  string `json:"expire_at"`
}
