// Code generated by goctl. DO NOT EDIT.
package types

type CreateURLRequest struct {
	OriginalRrl string `json:"original_url"`
	CustomCode  string `json:"custom_code,omitempty"`
	Duration    *int   `json:"duration,omitempty"`
}

type CreateURLResponse struct {
	ShortLink string `json:"short_link"`
	ExpireAt  string `json:"expire_at"`
}
