// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	"short_link_pro/sl_redict/redict_api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.ClientIPMiddleware},
			[]rest.Route{
				{
					Method:  http.MethodPost,
					Path:    "/api/redict/:shortUrl",
					Handler: ShowHandler(serverCtx),
				},
			}...,
		),
	)
}
